# Generated by Django 4.2.7 on 2024-02-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='slider',
            name='buttonText',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='buttonURL',
            field=models.URLField(blank=True, null=True, verbose_name='URL кнопки'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(to='shopApp.subcategory', verbose_name='Подкатегория'),
        ),
    ]
