# Generated by Django 4.2.7 on 2024-02-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_cart_for_anonymous_user_cart_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='products',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopApp.product', verbose_name='Продукты'),
            preserve_default=False,
        ),
    ]
