# Generated by Django 4.2.7 on 2024-02-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_remove_product_images_imageproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='related_image', to='shopApp.imageproduct', verbose_name='Изображение'),
        ),
    ]
